FROM node:22-bookworm-slim AS deps

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-bookworm-slim AS builder

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_ENV
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_WP_GRAPHQL_ENDPOINT
ARG NEXT_PUBLIC_TURNSTILE_SITE_KEY
ARG NEXT_PUBLIC_GTM_ID
ARG NEXT_PUBLIC_META_PIXEL_ID
ARG NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY
ARG NEXT_PUBLIC_ENABLE_SITEMAPS_PREVIEW
ARG NEXT_PUBLIC_ENABLE_GTM_PREVIEW
ARG WP_PROJECT_BASE
ARG YOUTUBE_API_KEY
ARG DIRECTUS_URL
ARG DIRECTUS_CLIENT_SLUG
ARG DIRECTUS_TOKEN

ENV NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV}
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ENV NEXT_PUBLIC_WP_GRAPHQL_ENDPOINT=${NEXT_PUBLIC_WP_GRAPHQL_ENDPOINT}
ENV NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
ENV NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID}
ENV NEXT_PUBLIC_META_PIXEL_ID=${NEXT_PUBLIC_META_PIXEL_ID}
ENV NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_EMBED_KEY}
ENV NEXT_PUBLIC_ENABLE_SITEMAPS_PREVIEW=${NEXT_PUBLIC_ENABLE_SITEMAPS_PREVIEW}
ENV NEXT_PUBLIC_ENABLE_GTM_PREVIEW=${NEXT_PUBLIC_ENABLE_GTM_PREVIEW}
ENV WP_PROJECT_BASE=${WP_PROJECT_BASE}
ENV YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
ENV DIRECTUS_URL=${DIRECTUS_URL}
ENV DIRECTUS_CLIENT_SLUG=${DIRECTUS_CLIENT_SLUG}
ENV DIRECTUS_TOKEN=${DIRECTUS_TOKEN}

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:22-bookworm-slim AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

RUN apt-get update \
  && apt-get install -y --no-install-recommends curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

RUN groupadd --system --gid 1001 nodejs \
  && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
